#!/usr/bin/env python3
"""Generate the drop-in preset workflows from the base graphs and the prompt library.

    scripts/build_presets.py            # write workflows/api/preset_*.json
    scripts/build_presets.py --check    # fail if any preset is out of date

The presets exist so the pipeline can be run ad hoc, from the ComfyUI sidebar,
without anyone having to remember which settings are load bearing.  Each one is
a base graph with the settled decisions already applied: the house style in the
positive prompt, the matching negative, the canvas shape that subject wants, and
a sampler configuration where those choices actually take effect.

They are GENERATED.  Edit the base graph or the prompt library and re-run this,
rather than editing a preset by hand.  `--check` is wired into
validate_workflows.py so a drifted preset is caught rather than shipped.

Every preset carries a SUBJECT placeholder in its positive prompt.  Replacing
that one line is the whole of the ad hoc workflow: type the subject, queue it.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
API = ROOT / "workflows" / "api"
PROMPTS = ROOT / "prompts"

PLACEHOLDER = "<<< SUBJECT: describe the one thing you want, then queue >>>"


def read(path: Path) -> str:
    return path.read_text().strip() if path.exists() else ""


def node_by_title(graph: dict, title: str) -> dict:
    for k, v in graph.items():
        if isinstance(v, dict) and v.get("_meta", {}).get("title") == title:
            return v
    raise SystemExit(f"no node titled {title!r} in the base graph")


def build(base: str, comment: str, edits: list[tuple[str, str, object]]) -> dict:
    graph = json.loads((API / base).read_text())
    graph["_comment"] = comment
    for title, key, value in edits:
        node_by_title(graph, title)["inputs"][key] = value
    return graph


# --- the presets -----------------------------------------------------------
def presets() -> dict[str, dict]:
    out: dict[str, dict] = {}

    # Concept art. 20 steps at guidance 4.0, NOT the 4-step fast graph: the
    # negative prompt below is what keeps ragged hems and clutter out, and at
    # the fast graph's guidance of 1.0 a negative prompt does nothing at all.
    # The icons folder ships no _style.txt: the look is short enough to state
    # once here, and every icon prompt in prompts/icons follows it.
    fallback_style = {
        "icons": (
            "One object only, centred in the frame with clear space around it, "
            "seen straight on. Painted storybook illustration with clean "
            "readable shapes and a bold silhouette, warm even lighting from the "
            "upper left, no cast shadow. Flat plain mid-grey background, empty."),
    }

    for name, folder, style_file, neg_file, w, h, prefix in [
        ("preset_concept_character", "characters", "_style.txt", "_negative.txt",
         1104, 1472, "concept/character"),
        ("preset_concept_creature", "creatures", "_style.txt", "_negative.txt",
         1104, 1472, "concept/creature"),
        ("preset_concept_building", "buildings", "_style.txt", "_negative.txt",
         1472, 1104, "concept/building"),
        ("preset_concept_prop", "scenery", "_style.txt", "_negative.txt",
         1104, 1104, "concept/prop"),
        ("preset_concept_icon", "icons", "_style.txt", "_negative.txt",
         1024, 1024, "concept/icon"),
    ]:
        style = read(PROMPTS / folder / style_file) or fallback_style.get(folder, "")
        neg = read(PROMPTS / folder / neg_file)
        shape = ("portrait" if h > w else "landscape" if w > h else "square")
        positive = f"{PLACEHOLDER}\n\n{style}" if style else PLACEHOLDER
        out[name] = build(
            "txt2img_qwen.json",
            f"DROP-IN PRESET: {folder} concept art, {shape} {w}x{h}. "
            f"Replace the first line of the Positive node with your subject and "
            f"queue. The house style and the negative prompt below it are already "
            f"set, and are the reason this uses the 20-step graph rather than the "
            f"4-step one: at the fast graph's cfg 1.0 the negative prompt is "
            f"ignored entirely. Generated by scripts/build_presets.py.",
            [("Positive", "text", positive),
             ("Negative", "text", neg),
             ("Latent", "width", w),
             ("Latent", "height", h),
             ("Save", "filename_prefix", prefix)])

    # Ground textures. Square, larger, and the prompt scaffold is most of the
    # work: every clause in it is preventing one specific failure.
    ground_scaffold = (
        "A seamless tileable ground texture of "
        f"{PLACEHOLDER}, photographed from directly overhead looking straight "
        "down. Fine even detail spread uniformly across the whole frame, the "
        "same density everywhere, no large shapes and no focal point, like a "
        "close macro crop of a much larger surface. Flat shadowless overcast "
        "light, painted game texture, crisp small-scale detail.")
    out["preset_ground_texture"] = build(
        "txt2img_qwen.json",
        "DROP-IN PRESET: tileable ground texture, 1024x1024. Replace only the "
        "SUBJECT phrase in the Positive node (e.g. 'dense woodland floor of "
        "fallen leaves, moss and twigs') and leave the rest of the sentence "
        "alone: every clause in it is preventing a specific failure, listed in "
        "docs/guide/terrain. The image is NOT tileable when it comes out of "
        "here. Run scripts/make_seamless.py on it afterwards. "
        "Generated by scripts/build_presets.py.",
        [("Positive", "text", ground_scaffold),
         ("Negative", "text", read(PROMPTS / "ground" / "_negative.txt")),
         ("Latent", "width", 1024),
         ("Latent", "height", 1024),
         ("Save", "filename_prefix", "ground/texture")])

    # Simplifying art you already have. 0.85 is the default because the knob
    # behaves as a cliff: 1.0 returns flat vector art however the prompt is
    # worded.
    out["preset_simplify_concept"] = build(
        "img_edit_qwen.json",
        "DROP-IN PRESET: simplify existing concept art into a game-ready "
        "version of the same picture. Load your image in the Source node and "
        "queue. denoise is the style knob and it is a cliff, not a slider: "
        "0.85 keeps the painterly rendering while cutting clutter, 0.93 pushes "
        "to clean game-ready forms, and 1.0 hands back flat vector art no "
        "matter what the prompt says. Test one image before batching. "
        "Generated by scripts/build_presets.py.",
        [("Positive", "prompt", read(PROMPTS / "unit_simplify.txt") or
          read(PROMPTS / "lord_simplify.txt")),
         ("Sampler", "denoise", 0.85),
         ("Save", "filename_prefix", "simplified/asset")])

    # Facing sheets. The azimuths are the whole point of these two, and they
    # are the thing people get wrong: an isometric camera looks down the
    # diagonal BETWEEN the world axes, so a unit facing a world direction has
    # to be rendered at 45/135/225/315, not 0/90/180/270.
    out["preset_sprites_iso_8"] = build(
        "mesh_render_sprites.json",
        "DROP-IN PRESET: 8 facings for a 2:1 isometric map. Elevation 30 is "
        "arcsin(0.5), the only angle at which a model's ground plane lands "
        "square on a 2:1 diamond. Azimuths start at 45 because an isometric "
        "camera looks down the diagonal between the world axes. Point the Load "
        "node at your mesh and queue. NOTE: this renderer is perspective, which "
        "is fine for a turnaround and wrong for sprites that must match each "
        "other in scale. Use scripts/render_sheet.py for anything the game "
        "loads. Generated by scripts/build_presets.py.",
        [("Camera Poses", "elevation_start", 30.0),
         ("Camera Poses", "elevation_stop", 30.0),
         ("Camera Poses", "elevation_step", 0.0),
         ("Camera Poses", "azimuth_start", 45.0),
         ("Camera Poses", "azimuth_stop", 360.0),
         ("Camera Poses", "azimuth_step", 45.0),
         ("Save Sprites", "filename_prefix", "sprites/iso")])

    out["preset_sprites_topdown_8"] = build(
        "mesh_render_sprites.json",
        "DROP-IN PRESET: 8 facings for a top-down or three-quarter overhead "
        "game. Elevation 60 suits a 4:3-ish overhead view; for a true straight-"
        "down camera use scripts/render_sheet.py --elevation 90. Azimuths start "
        "at 0 because a top-down camera looks along the world axes rather than "
        "between them, which is the opposite of the isometric case. "
        "Generated by scripts/build_presets.py.",
        [("Camera Poses", "elevation_start", 60.0),
         ("Camera Poses", "elevation_stop", 60.0),
         ("Camera Poses", "elevation_step", 0.0),
         ("Camera Poses", "azimuth_start", 0.0),
         ("Camera Poses", "azimuth_stop", 315.0),
         ("Camera Poses", "azimuth_step", 45.0),
         ("Save Sprites", "filename_prefix", "sprites/topdown")])

    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="do not write; exit 1 if any preset differs from what "
                         "would be generated")
    args = ap.parse_args()

    stale = []
    for name, graph in presets().items():
        path = API / f"{name}.json"
        text = json.dumps(graph, indent=2) + "\n"
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(name)
            continue
        path.write_text(text)
        print(f"  wrote workflows/api/{name}.json")

    if args.check:
        if stale:
            print("  out of date: " + ", ".join(stale), file=sys.stderr)
            print("  run scripts/build_presets.py", file=sys.stderr)
            return 1
        print(f"  {len(presets())} presets up to date")
    else:
        print()
        print("  Now convert them for the editor sidebar:")
        print("    scripts/api_to_ui.py --check")
    return 0


if __name__ == "__main__":
    sys.exit(main())
