#!/usr/bin/env python3
"""Check that every skill, graph, script and docs page is listed everywhere it is listed.

    scripts/check_docs_sync.py
    scripts/check_docs_sync.py --untracked    # also count scripts and pages git does not track yet

WHY: the same names are kept by hand in several places.  A skill is named in two
tables in README.md, two in docs/guide/claude.md and one in
docs/reference/skills.md, and counted twice in claude.md.  A graph needs a
_comment, a row in docs/reference/workflows.md and a NOTES entry in
scripts/api_to_ui.py.  Commit d0be433 added the game-music skill, and 4c1fab4
then had to add it to README.md, docs/guide/claude.md and both plugin manifests.
Nothing failed in between, because VitePress reads neither skills/ nor README.md.
This script is the thing that fails.

It prints one line per problem and exits 1 if there are any.  Standard library
only.  It reads files, parses scripts/api_to_ui.py without importing it, and runs
`git ls-files`; it never touches the network or the ComfyUI server.

What is compared:

- skills/<name>/SKILL.md: the frontmatter name is the folder name, and the name
  has a row in every skill table (a column headed Skill or Runs) in README.md,
  docs/guide/claude.md and docs/reference/skills.md.  claude.md's "ships <n>
  skills" and its "Skills (N)" inventory line match the count, and the inventory
  lists every name.  A "Skills (N)" in CLAUDE.md, if it has one, matches too.
- workflows/api/*.json: each has a _comment and a row in
  docs/reference/workflows.md, and each non-preset graph has a NOTES entry.
- scripts/*.py and scripts/*.sh tracked by git: each has a row in
  docs/reference/scripts.md.
- docs/**/*.md tracked by git: each has a sidebar link in docs/.vitepress/config.ts.

Rows, NOTES entries and sidebar links that name something which no longer exists
are reported too.  Skills and graphs are read from disk, because that is what the
plugin and the server load; scripts and pages come from git, so untracked work in
progress is left alone unless --untracked is given.

WHAT IT WILL NOT TELL YOU: whether anything a row says is true.  It checks that a
name is present, not that its description, licence, timing or count still matches
what the thing does.  Plugin manifest descriptions and keywords are prose and are
not checked; `claude plugin validate .` and `claude --plugin-dir . plugin details
game-asset-engine` are the checks for those.
"""
from __future__ import annotations

import argparse
import ast
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------- allowlists
# Each entry says why the rule does not apply.  Add one only with a reason.

# Tracked scripts that need no row in docs/reference/scripts.md.
SCRIPTS_WITHOUT_ROW = {
    "_engine.py": "shared helper the other scripts import to find the container; "
                  "scripts.md describes it in prose under 'Where scripts run'",
}

# Tracked pages under docs/ that need no sidebar link.
PAGES_WITHOUT_SIDEBAR = {
    "docs/index.md": "the home page, reached from the logo; it has no sidebar",
}

# Graph name prefixes that need no NOTES entry in scripts/api_to_ui.py.
GRAPHS_WITHOUT_NOTES = {
    "preset_": "generated by scripts/build_presets.py, which writes what each one "
               "bakes in to its _comment",
}

# How many skill tables each file must hold.  Fewer means a table was removed or
# its header renamed, and the check would otherwise pass without looking.
SKILL_TABLES = {
    "README.md": 2,
    "docs/guide/claude.md": 2,
    "docs/reference/skills.md": 1,
}
SKILL_COLUMNS = ("Skill", "Runs")

NUMBER_WORDS = {w: i for i, w in enumerate(
    "zero one two three four five six seven eight nine ten eleven twelve "
    "thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty".split())}

CLAUDE_GUIDE = "docs/guide/claude.md"
SCRIPTS_PAGE = "docs/reference/scripts.md"
WORKFLOWS_PAGE = "docs/reference/workflows.md"
SIDEBAR = "docs/.vitepress/config.ts"
NOTES_FILE = "scripts/api_to_ui.py"


# ------------------------------------------------------------------- helpers

def read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8")


def line_of(text: str, pos: int) -> int:
    return text.count("\n", 0, pos) + 1


def git_files(pathspec: str, untracked: bool) -> list[str]:
    """Paths git tracks under pathspec, plus untracked ones when asked."""
    cmds = [["ls-files", "-z", "--", pathspec]]
    if untracked:
        cmds.append(["ls-files", "-z", "--others", "--exclude-standard", "--", pathspec])
    out: set[str] = set()
    for cmd in cmds:
        try:
            res = subprocess.run(["git", "-C", str(ROOT), *cmd],
                                 capture_output=True, check=True)
        except (OSError, subprocess.CalledProcessError) as e:
            err = getattr(e, "stderr", b"") or b""
            sys.exit(f"check_docs_sync: git ls-files failed, run this from a git "
                     f"checkout: {err.decode(errors='replace').strip() or e}")
        out.update(p for p in res.stdout.decode().split("\0") if p)
    return sorted(out)


def tables(rel: str):
    """Yield (line, header_cells, rows) for each pipe table outside code fences.

    rows is a list of (line, cells).  Cells are split on unescaped pipes."""
    fence = False
    block: list[tuple[int, str]] = []

    def flush():
        if len(block) >= 2 and re.fullmatch(r"\|?[\s:|-]+\|?", block[1][1].strip()):
            split = [(n, [c.strip() for c in re.split(r"(?<!\\)\|", s.strip().strip("|"))])
                     for n, s in block]
            yield split[0][0], split[0][1], split[2:]

    for n, raw in enumerate(read(rel).splitlines(), 1):
        if raw.lstrip().startswith(("```", "~~~")):
            fence = not fence
        if not fence and raw.lstrip().startswith("|"):
            block.append((n, raw))
            continue
        yield from flush()
        block = []
    yield from flush()


def first_code(cell: str) -> str | None:
    m = re.search(r"`([^`]+)`", cell)
    return m.group(1) if m else None


def first_column_names(rel: str) -> dict[str, int]:
    """Backticked names in the first cell of every table row, with their lines."""
    names: dict[str, int] = {}
    for _, _, rows in tables(rel):
        for n, cells in rows:
            name = first_code(cells[0]) if cells else None
            if name:
                names.setdefault(name, n)
    return names


# -------------------------------------------------------------------- checks

def check_skills(problems: list[str]) -> int:
    skills: list[str] = []
    for md in sorted(ROOT.glob("skills/*/SKILL.md")):
        folder = md.parent.name
        rel = md.relative_to(ROOT).as_posix()
        skills.append(folder)
        text = md.read_text(encoding="utf-8")
        m = re.match(r"---\r?\n(.*?)\r?\n---\r?\n", text, re.S)
        if not m:
            problems.append(f"{rel}: no frontmatter between --- lines")
            continue
        nm = re.search(r"^name:\s*['\"]?([^'\"\n]*?)['\"]?\s*$", m.group(1), re.M)
        if not nm:
            problems.append(f"{rel}: frontmatter has no name")
        elif nm.group(1) != folder:
            problems.append(f"{rel}:{line_of(text, m.start(1) + nm.start())}: "
                            f"frontmatter name is {nm.group(1)}, folder is {folder}")
    want = set(skills)

    for rel, expected in SKILL_TABLES.items():
        found = 0
        for hline, header, rows in tables(rel):
            cols = [i for i, h in enumerate(header) if h in SKILL_COLUMNS]
            if not cols:
                continue
            found += 1
            col, label = cols[0], " | ".join(header)
            # A Skill table lists each skill once.  A Runs table maps example
            # phrases to skills, so one skill may have several rows there.
            one_row_each = header[col] == "Skill"
            seen: dict[str, int] = {}
            for n, cells in rows:
                name = first_code(cells[col]) if col < len(cells) else None
                if name is None:
                    problems.append(f"{rel}:{n}: row in table '{label}' names no skill "
                                    f"in its {header[col]} column")
                elif name in seen and one_row_each:
                    problems.append(f"{rel}:{n}: table '{label}' lists {name} twice")
                elif name not in want and name not in seen:
                    problems.append(f"{rel}:{n}: table '{label}' lists {name}, which "
                                    f"has no skills/{name}/SKILL.md")
                if name:
                    seen.setdefault(name, n)
            for name in sorted(want - set(seen)):
                problems.append(f"{rel}:{hline}: table '{label}' has no row for {name}")
        if found < expected:
            problems.append(f"{rel}: expected {expected} skill tables (a column headed "
                            f"{' or '.join(SKILL_COLUMNS)}), found {found}")

    text = read(CLAUDE_GUIDE)
    count = "|".join(NUMBER_WORDS) + r"|\d+"
    m = re.search(rf"\bships\s+({count})\s+skills\b", text, re.I)
    if not m:
        problems.append(f"{CLAUDE_GUIDE}: no 'ships <n> skills' sentence to check")
    else:
        word = m.group(1).lower()
        n = int(word) if word.isdigit() else NUMBER_WORDS.get(word)
        if n != len(skills):
            problems.append(f"{CLAUDE_GUIDE}:{line_of(text, m.start())}: says it ships "
                            f"{m.group(1)} skills, but skills/ holds {len(skills)}")
    m = re.search(r"^\s*Skills \((\d+)\)[ \t]*(.*)$", text, re.M)
    if not m:
        problems.append(f"{CLAUDE_GUIDE}: no 'Skills (N)' inventory line to check")
    else:
        where = f"{CLAUDE_GUIDE}:{line_of(text, m.start(1))}"
        if int(m.group(1)) != len(skills):
            problems.append(f"{where}: inventory says Skills ({m.group(1)}), but skills/ "
                            f"holds {len(skills)}")
        listed = {s.strip() for s in m.group(2).split(",") if s.strip()}
        for name in sorted(want - listed):
            problems.append(f"{where}: inventory does not list {name}")
        for name in sorted(listed - want):
            problems.append(f"{where}: inventory lists {name}, which has no "
                            f"skills/{name}/SKILL.md")
    if (ROOT / "CLAUDE.md").is_file():
        text = read("CLAUDE.md")
        for m in re.finditer(r"\bSkills \((\d+)\)", text):
            if int(m.group(1)) != len(skills):
                problems.append(f"CLAUDE.md:{line_of(text, m.start())}: says Skills "
                                f"({m.group(1)}), but skills/ holds {len(skills)}")
    return len(skills)


def notes_keys(problems: list[str]) -> dict[str, int] | None:
    text = read(NOTES_FILE)
    for node in ast.parse(text, NOTES_FILE).body:
        targets = (node.targets if isinstance(node, ast.Assign)
                   else [node.target] if isinstance(node, ast.AnnAssign) else [])
        if any(isinstance(t, ast.Name) and t.id == "NOTES" for t in targets):
            if not isinstance(node.value, ast.Dict):
                break
            keys = {}
            for k in node.value.keys:
                if isinstance(k, ast.Constant) and isinstance(k.value, str):
                    keys[k.value] = k.lineno
                else:
                    problems.append(f"{NOTES_FILE}:{getattr(k, 'lineno', node.lineno)}: "
                                    f"NOTES key is not a plain string")
            return keys
    problems.append(f"{NOTES_FILE}: no module-level NOTES dict literal found")
    return None


def check_graphs(problems: list[str]) -> int:
    graphs = sorted(ROOT.glob("workflows/api/*.json"))
    names = {p.stem for p in graphs}
    rows = first_column_names(WORKFLOWS_PAGE)
    notes = notes_keys(problems)

    for p in graphs:
        rel = p.relative_to(ROOT).as_posix()
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
        except (ValueError, UnicodeDecodeError) as e:
            problems.append(f"{rel}: not valid JSON: {e}")
            data = None
        if data is not None:
            comment = data.get("_comment") if isinstance(data, dict) else None
            if not (isinstance(comment, str) and comment.strip()):
                problems.append(f"{rel}: no _comment saying what the graph does")
        if p.name not in rows:
            problems.append(f"{WORKFLOWS_PAGE}: no row for {p.name}")
        exempt = any(p.stem.startswith(pre) for pre in GRAPHS_WITHOUT_NOTES)
        if notes is not None and not exempt and p.stem not in notes:
            problems.append(f"{NOTES_FILE}: NOTES has no entry for {p.stem}")

    for name, n in sorted(rows.items()):
        if name.endswith(".json") and Path(name).stem not in names:
            problems.append(f"{WORKFLOWS_PAGE}:{n}: row for {name}, which is not in "
                            f"workflows/api/")
    for key, n in sorted((notes or {}).items()):
        if key not in names:
            problems.append(f"{NOTES_FILE}:{n}: NOTES entry {key} has no "
                            f"workflows/api/{key}.json")
    return len(graphs)


def check_scripts(problems: list[str], untracked: bool) -> int:
    scripts = [Path(p).name for p in git_files("scripts", untracked)
               if re.fullmatch(r"scripts/[^/]+\.(py|sh)", p)]
    rows = first_column_names(SCRIPTS_PAGE)
    for name in scripts:
        if name not in rows and name not in SCRIPTS_WITHOUT_ROW:
            problems.append(f"{SCRIPTS_PAGE}: no row for {name}")
    for name, n in sorted(rows.items()):
        if re.fullmatch(r"[^/]+\.(py|sh)", name) and not (ROOT / "scripts" / name).is_file():
            problems.append(f"{SCRIPTS_PAGE}:{n}: row for {name}, which is not in scripts/")
    return len(scripts)


def page_link(rel: str) -> str:
    link = "/" + rel[len("docs/"):-len(".md")]
    return link[:-len("index")] if link.endswith("/index") else link


def check_sidebar(problems: list[str], untracked: bool) -> int:
    text = read(SIDEBAR)
    start = text.find("sidebar:")
    if start < 0:
        problems.append(f"{SIDEBAR}: no sidebar: block found")
        return 0
    links: dict[str, int] = {}
    for m in re.finditer(r"\blink:\s*['\"](/[^'\"]*)['\"]", text[start:]):
        # The page a link opens: no #anchor or ?query, and no .md or .html ending.
        path = re.sub(r"\.(md|html)$", "", re.split(r"[#?]", m.group(1), maxsplit=1)[0])
        links.setdefault(path.rstrip("/") or "/", line_of(text, start + m.start()))

    pages = [p for p in git_files("docs", untracked)
             if p.endswith(".md") and not p.startswith("docs/.vitepress/")]
    for rel in pages:
        link = page_link(rel).rstrip("/") or "/"
        if link not in links and rel not in PAGES_WITHOUT_SIDEBAR:
            problems.append(f"{SIDEBAR}: no sidebar link to {page_link(rel)} ({rel})")
    for link, n in sorted(links.items()):
        base = ROOT / "docs" / link.lstrip("/")
        # Append .md rather than use with_suffix, which would cut a name at its
        # last dot, such as a page called v0.1.2.
        if not (Path(f"{base}.md").is_file() or (base / "index.md").is_file()):
            problems.append(f"{SIDEBAR}:{n}: sidebar link {link} has no page under docs/")
    return len(pages)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--untracked", action="store_true",
                    help="count scripts and docs pages git does not track yet "
                         "(ignored files stay ignored)")
    args = ap.parse_args()

    problems: list[str] = []
    n_skills = check_skills(problems)
    n_graphs = check_graphs(problems)
    n_scripts = check_scripts(problems, args.untracked)
    n_pages = check_sidebar(problems, args.untracked)

    for p in problems:
        print(p)
    sys.stdout.flush()
    if problems:
        print(f"{len(problems)} problem(s)", file=sys.stderr)
        return 1
    print(f"in sync: {n_skills} skills, {n_graphs} graphs, {n_scripts} scripts, "
          f"{n_pages} pages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
