#!/usr/bin/env python3
"""Keep the four things worth keeping from a generated asset; sweep the rest.

A finished asset is a **concept image**, a **model**, its **textures** and its
**pose sheets**. Everything else under output/ is scratch: per-frame renders that
were composed into a sheet, unlit silhouette checks, UV working files, rejected
concepts, superseded meshes.

Nothing on disk records which concept produced which mesh (the filenames are
counters and timestamps), so this tool never guesses. You name the keepers once,
they are copied into `output/assets/<name>/`, and only then is anything swept.

    # 1. see what is scratch, what is protected, and what is unclaimed
    scripts/cleanup.py

    # 2. curate one asset (copies, never moves)
    scripts/cleanup.py keep warrior \\
        --concept output/concept/qwen_00002_.png \\
        --model   output/mesh/textured_2026-09-08-22-22-18.glb \\
        --rig     output/rigged/warrior.fbx \\
        --sheets  output/sheets/warrior_walk.png output/sheets/warrior_attack.png

    #    and record where it came from, copying licence and URL from models.json.
    #    The Nth of each flag belong together: this records two rows.
    scripts/cleanup.py keep warrior --concept output/concept/qwen_00002_.png \\
        --generator txt2img_qwen --source Qwen/Qwen-Image \\
        --licence Apache-2.0 --licence-url https://huggingface.co/Qwen/Qwen-Image \\
        --generator img2mesh_hunyuan3d21 --source tencent/Hunyuan3D-2.1 \\
        --licence 'Tencent Hunyuan Community' \\
        --licence-url https://huggingface.co/tencent/Hunyuan3D-2.1/blob/main/LICENSE

    # 3. sweep
    scripts/cleanup.py sweep            # dry run - always
    scripts/cleanup.py sweep --delete   # scratch only
    scripts/cleanup.py sweep --delete --unclaimed   # also anything not curated,
                                                    # outside the protected folders

The protected folders under output/ (music, icons, scenery, ground, materials,
lipsync and mpfb) hold finished work that `keep` has no way to claim, so
--unclaimed leaves them alone unless you also pass --include-protected.

--generator, --source, --licence and --licence-url record where an asset came
from, as rows in the "provenance" list of its sources.json. Each row has a
generator, source, licence and licence_url field. The flags are repeatable, and
the Nth use of each makes row N, so every flag you use must be given the same
number of times; `keep` refuses mismatched counts rather than pair a source
with the wrong licence. A later `keep` of the same name appends its rows and
skips only a row that is already recorded whole. A flag you leave out records
nothing: no field is ever filled with a guess.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "output"
ASSETS = OUT / "assets"

# Pure by-products. Regenerated by re-running the step that made them, so they
# are never worth a confirmation prompt.
SCRATCH_DIRS = [
    ("_sheet_frames", "per-frame renders, recomposed into a sheet every run"),
    ("sprites", "unlit ComfyUI silhouette checks"),
    ("Hun2-1", "Hunyuan3D TexGen's working directory; the maps are baked into the textured .glb"),
]
SCRATCH_EXTRA = [
    (ROOT / "logs", "run logs from setup.sh / postinstall.sh and any redirected run"),
]
SCRATCH_GLOBS = [
    ("**/*_uv.npz", "UV working files written by Load 3D Mesh"),
    ("**/*.part", "interrupted downloads"),
    ("**/*.bak", "backups"),
]

# Finished work that `keep` cannot claim: it curates a concept, a model, a rig,
# sheets and textures, and has no slot for a music take, an icon, a prop, a
# ground tile, a material, a mouth set or a MakeHuman body. Without this list
# every file in them reads as unclaimed, and `sweep --delete --unclaimed` would
# delete them. They are skipped unless the sweep is given --include-protected.
# The module docstring names these folders too; --include-protected's help is
# built from this list.
PROTECTED_DIRS = [
    ("music", "music takes and loops from generate_music.py"),
    ("icons", "icon concepts and the icons cut from them"),
    ("scenery", "scenery prop concepts"),
    ("ground", "ground texture takes, the input to make_seamless.py"),
    ("materials", "seamless materials written by make_seamless.py"),
    ("lipsync", "mouth sets, timelines and MP4 previews from make_mouths.py, "
                "compose_mouths.py, lipsync_cues.py and preview_lipsync.py; a set's "
                "manifest.json only works beside its own overlays"),
    ("mpfb", "MakeHuman bodies with viseme shape keys, and their sheets, from "
             "mpfb_probe.py; keep needs a concept image, which a built body lacks"),
]

# Provenance flags on `keep`, as (row key in sources.json, argparse dest).
PROVENANCE = [
    ("generator", "generator"),
    ("source", "source"),
    ("licence", "licence"),
    ("licence_url", "licence_url"),
]


def human(n: float) -> str:
    for u in ("B", "KB", "MB", "GB"):
        if n < 1024 or u == "GB":
            return f"{n:.0f}{u}" if u == "B" else f"{n:.1f}{u}"
        n /= 1024.0
    return ""


def size_of(p: Path) -> int:
    if p.is_file():
        return p.stat().st_size
    return sum(f.stat().st_size for f in p.rglob("*") if f.is_file())


def find_scratch() -> list[tuple[Path, str]]:
    hits: list[tuple[Path, str]] = []
    for name, why in SCRATCH_DIRS:
        d = OUT / name
        if d.is_dir():
            hits.append((d, why))
    for d, why in SCRATCH_EXTRA:
        if d.is_dir() and any(f for f in d.iterdir() if f.name != ".gitkeep"):
            hits.append((d, why))
    for pattern, why in SCRATCH_GLOBS:
        for f in OUT.glob(pattern):
            if ASSETS in f.parents:
                continue                      # curated copies are never scratch
            hits.append((f, why))
    return hits


def find_protected() -> list[tuple[Path, str, int, int]]:
    """(folder, why, file count, bytes) for each protected folder that exists."""
    hits = []
    for name, why in PROTECTED_DIRS:
        d = OUT / name
        if d.is_dir():
            files = [f for f in d.rglob("*") if f.is_file()]
            hits.append((d, why, len(files), sum(f.stat().st_size for f in files)))
    return hits


def curated_files() -> set[Path]:
    if not ASSETS.is_dir():
        return set()
    return {f.resolve() for f in ASSETS.rglob("*") if f.is_file()}


def curated_sources() -> set[Path]:
    """The ORIGINAL paths that have been curated, read from each asset's
    sources.json.

    Matching on basenames instead would be wrong and dangerous: `keep` renames
    as it copies (concept.png, model.glb, rig.fbx), so the originals would never
    match their copies and --unclaimed would offer to delete the very files that
    were just curated."""
    out: set[Path] = set()
    if not ASSETS.is_dir():
        return out
    for man in ASSETS.glob("*/sources.json"):
        try:
            for rel in json.loads(man.read_text()).get("sources", []):
                out.add((ROOT / rel).resolve())
        except (OSError, ValueError, AttributeError):
            print(f"  ! could not read {man.relative_to(ROOT)}; treating its "
                  f"sources as unclaimed", file=sys.stderr)
    return out


def find_unclaimed(include_protected: bool = False) -> list[Path]:
    """Generated files outside output/assets/ that no curated copy matches.

    The protected folders are left out unless [include_protected]."""
    claimed = curated_sources()
    skip_roots = {OUT / n for n, _ in SCRATCH_DIRS}
    if not include_protected:
        skip_roots |= {OUT / n for n, _ in PROTECTED_DIRS}
    out: list[Path] = []
    for f in OUT.rglob("*"):
        if not f.is_file():
            continue
        if ASSETS in f.parents or any(r in f.parents or r == f for r in skip_roots):
            continue
        if f.resolve() in claimed:
            continue
        out.append(f)
    return sorted(out)


# --------------------------------------------------------------------- keep

def _as_list(value) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(v) for v in value]
    return [str(value)]


def provenance_rows(args) -> list[dict]:
    """One row per position: the Nth --generator, --source, --licence and
    --licence-url make row N.

    Values are never stored as four independent lists, because removing a
    repeated licence from one list would shift it against the sources and
    give a source someone else's licence. A flag that was not given is left
    out of every row; mismatched counts are refused, not padded or guessed."""
    given = {key: _as_list(getattr(args, dest_attr, None))
             for key, dest_attr in PROVENANCE}
    given = {key: values for key, values in given.items() if values}
    if not given:
        return []
    counts = {len(values) for values in given.values()}
    if len(counts) > 1:
        flags = ", ".join(f"--{key.replace('_', '-')} {len(values)} "
                          f"time{'' if len(values) == 1 else 's'}"
                          for key, values in given.items())
        sys.exit(f"keep: got {flags}. Give each provenance flag you use the same "
                 "number of times: the Nth of each form one row, so unequal counts "
                 "cannot say which licence belongs to which source. Nothing was copied.")
    return [{key: values[i] for key, values in given.items()}
            for i in range(counts.pop())]


def merge_rows(prior: list[dict], new: list[dict]) -> tuple[list[dict], int]:
    """Prior rows first, then each new row that is not already recorded whole.

    A row is only ever dropped as a duplicate of an identical row, never
    because one of its fields matches another row's. Returns the rows and how
    many were added."""
    rows = list(prior)
    added = 0
    for row in new:
        if row not in rows:
            rows.append(row)
            added += 1
    return rows, added


def read_prior(man: Path) -> dict:
    """The sources.json an earlier keep wrote, or {} when there is none.

    Refuses a file it cannot read rather than overwrite it, because it may
    hold the only record of where the asset came from and under which licence."""
    if not man.exists():
        return {}
    try:
        prior = json.loads(man.read_text())
    except (OSError, ValueError) as e:
        sys.exit(f"keep: could not read {man} ({e}). It may hold the asset's "
                 "provenance, so it is not overwritten. Fix or move it, then keep "
                 "again. Nothing was copied.")
    rows = prior.get("provenance", []) if isinstance(prior, dict) else None
    if not isinstance(rows, list) or not all(isinstance(r, dict) for r in rows):
        sys.exit(f"keep: {man} is not an object with a list of provenance rows, so it "
                 "is not overwritten. Fix or move it, then keep again. Nothing was "
                 "copied.")
    return prior


def cmd_keep(args) -> int:
    # Both checks come before anything is copied, so a refused keep leaves the
    # asset untouched.
    new_rows = provenance_rows(args)
    dest = ASSETS / args.name
    man = dest / "sources.json"
    prior = read_prior(man)

    tex = dest / "textures"
    dest.mkdir(parents=True, exist_ok=True)

    sources: list[str] = []

    def take(src: Path, into: Path, rename: str | None = None) -> None:
        if not src.exists():
            sys.exit(f"no such file: {src}")
        into.mkdir(parents=True, exist_ok=True)
        target = into / (rename or src.name)
        if src.resolve() == target.resolve():
            # Re-curating in place, e.g. to backfill sources.json after the
            # original was swept.  Record it, do not copy a file onto itself.
            print(f"  kept  {target.relative_to(ROOT)}  (already in place)")
            sources.append(str(target.resolve().relative_to(ROOT)))
            return
        shutil.copy2(src, target)
        try:
            sources.append(str(src.resolve().relative_to(ROOT)))
        except ValueError:
            sources.append(str(src.resolve()))
        print(f"  kept  {target.relative_to(ROOT)}  ({human(size_of(target))})")

    take(Path(args.concept), dest, f"concept{Path(args.concept).suffix}")
    if args.model:
        take(Path(args.model), dest, f"model{Path(args.model).suffix}")
    if args.rig:
        take(Path(args.rig), dest, f"rig{Path(args.rig).suffix}")
    for s in args.sheets or []:
        take(Path(s), dest / "sheets")

    # Sidecar maps: an .obj's .mtl and *_albedo/_metallic/_roughness images, and
    # anything TexGen left beside the model.  A .glb embeds its textures, so this
    # is usually empty for one, which is not an error.
    if args.model:
        model = Path(args.model)
        for extra in sorted(model.parent.glob(model.stem + "*")):
            if extra == model or extra.suffix.lower() in (".npz",):
                continue
            take(extra, tex)
    for t in args.textures or []:
        take(Path(t), tex)

    merged = sorted(set(_as_list(prior.get("sources"))) | set(sources))
    record: dict = {"name": args.name, "sources": merged}
    # Provenance merges like `sources`: the rows an earlier keep recorded stay,
    # and this keep's rows are appended unless the identical row is already
    # there. With no rows at all the key is left out, never written as "unknown".
    rows, added = merge_rows(prior.get("provenance", []), new_rows)
    if rows:
        record["provenance"] = rows
    # Anything else someone added to the file by hand is kept as it was.
    for key, value in prior.items():
        if key not in ("name", "sources", "provenance"):
            record[key] = value
    man.write_text(json.dumps(record, indent=2) + "\n")
    print(f"  wrote {man.relative_to(ROOT)}  ({len(merged)} source paths"
          + (f"; {len(rows)} provenance row{'' if len(rows) == 1 else 's'}, "
             f"{added} new)" if rows else ")"))

    print(f"\n{args.name} curated in {dest.relative_to(ROOT)}")
    print("Now: scripts/cleanup.py sweep            (dry run)")
    print("     scripts/cleanup.py sweep --delete   (scratch only)")
    return 0


# -------------------------------------------------------------------- sweep

def cmd_sweep(args) -> int:
    include_protected = getattr(args, "include_protected", False)

    scratch = find_scratch()
    total = sum(size_of(p) for p, _ in scratch)
    print(f"SCRATCH: always safe, regenerated by re-running the step ({human(total)})")
    if not scratch:
        print("  (none)")
    for p, why in scratch:
        print(f"  {human(size_of(p)):>8}  {p.relative_to(ROOT)}\n            {why}")

    protected = find_protected()
    pfiles = sum(n for _, _, n, _ in protected)
    pbytes = sum(b for _, _, _, b in protected)
    print(f"\nPROTECTED: finished work `keep` cannot claim ({human(pbytes)}, {pfiles} files)")
    if include_protected:
        print("  --include-protected was given, so these are IN the unclaimed list below.")
    else:
        print("  Never swept. Copy out what you want, then add --include-protected to sweep them.")
    if not protected:
        print("  (none)")
    for d, why, n, b in protected:
        print(f"  {human(b):>8}  {d.relative_to(ROOT)}  ({n} file{'' if n == 1 else 's'})\n"
              f"            {why}")

    unclaimed = find_unclaimed(include_protected=include_protected)
    utotal = sum(size_of(p) for p in unclaimed)
    print(f"\nUNCLAIMED: generated, but not curated into output/assets/ ({human(utotal)}, "
          f"{len(unclaimed)} files)")
    if not curated_files():
        print("  Nothing has been curated yet, so EVERYTHING is unclaimed.")
        print("  Run `scripts/cleanup.py keep <name> --concept ... --model ...` first.")
    for p in unclaimed[:20]:
        print(f"  {human(size_of(p)):>8}  {p.relative_to(ROOT)}")
    if len(unclaimed) > 20:
        print(f"  ... and {len(unclaimed) - 20} more")

    targets = [p for p, _ in scratch]
    if args.unclaimed:
        targets += unclaimed

    if not args.delete:
        print(f"\nDry run. {human(sum(size_of(p) for p in targets))} would be removed.")
        print("Add --delete to act" + (", and --unclaimed to include the UNCLAIMED list."
                                       if not args.unclaimed else "."))
        return 0

    if args.unclaimed and not curated_files():
        sys.exit("\nRefusing --unclaimed with nothing curated: that would delete every "
                 "asset you have made. Run `cleanup.py keep ...` first.")

    freed = 0
    for p in targets:
        try:
            n = size_of(p)
            if p.is_dir():
                shutil.rmtree(p)
            else:
                p.unlink()
        except FileNotFoundError:
            continue                      # already gone; nothing to report
        freed += n
        print(f"  removed {p.relative_to(ROOT)}")
    print(f"\nFreed {human(freed)}.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd")

    k = sub.add_parser("keep", help="curate one asset into output/assets/<name>/")
    k.add_argument("name")
    k.add_argument("--concept", required=True, help="the base image")
    k.add_argument("--model", help="the mesh (.glb/.obj), textured if you have one. "
                   "Omit for a concept-only asset that has not been through image-to-3D yet")
    k.add_argument("--rig", help="the rigged .fbx, if there is one")
    k.add_argument("--sheets", nargs="*", help="pose sheets to keep")
    k.add_argument("--textures", nargs="*", help="extra texture maps not beside the model")
    prov = k.add_argument_group(
        "provenance",
        "Recorded as rows in sources.json. Each flag is repeatable, and the Nth use "
        "of each makes row N, so give every flag you use the same number of times.")
    prov.add_argument("--generator", action="append", metavar="NAME",
                      help="the workflow or script that made it, e.g. txt2img_qwen")
    prov.add_argument("--source", action="append", metavar="MODEL",
                      help="the upstream model or asset base, e.g. Qwen/Qwen-Image")
    prov.add_argument("--licence", action="append", metavar="LICENCE",
                      help="the licence of that row's source, e.g. Apache-2.0")
    prov.add_argument("--licence-url", dest="licence_url", action="append", metavar="URL",
                      help="where that row's licence text is")
    k.set_defaults(func=cmd_keep)

    s = sub.add_parser("sweep", help="report, then optionally remove")
    s.add_argument("--delete", action="store_true", help="actually remove (default: dry run)")
    s.add_argument("--unclaimed", action="store_true",
                   help="also remove generated files not curated into output/assets/, "
                        "outside the protected folders")
    s.add_argument("--include-protected", action="store_true",
                   help="count the protected folders under output/ ("
                        + ", ".join(name for name, _ in PROTECTED_DIRS)
                        + ") as unclaimed too, so --unclaimed deletes them")
    s.set_defaults(func=cmd_sweep)

    args = ap.parse_args()
    if not args.cmd:
        return cmd_sweep(argparse.Namespace(delete=False, unclaimed=False,
                                            include_protected=False))
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
