#!/usr/bin/env python3
"""Keep the four things worth keeping from a generated asset; sweep the rest.

A finished asset is a **concept image**, a **model**, its **textures** and its
**pose sheets**. Everything else under output/ is scratch: per-frame renders that
were composed into a sheet, unlit silhouette checks, UV working files, rejected
concepts, superseded meshes.

Nothing on disk records which concept produced which mesh — the filenames are
counters and timestamps — so this tool never guesses. You name the keepers once,
they are copied into `output/assets/<name>/`, and only then is anything swept.

    # 1. see what is scratch, and what is unclaimed
    scripts/cleanup.py

    # 2. curate one asset (copies, never moves)
    scripts/cleanup.py keep warrior \\
        --concept output/concept/qwen_00002_.png \\
        --model   output/mesh/textured_2026-09-08-22-22-18.glb \\
        --rig     output/rigged_1788911741_articulationxl.fbx \\
        --sheets  output/sheets/warrior_walk.png output/sheets/warrior_attack.png

    # 3. sweep
    scripts/cleanup.py sweep            # dry run - always
    scripts/cleanup.py sweep --delete   # scratch only
    scripts/cleanup.py sweep --delete --unclaimed   # also anything not curated
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "output"
ASSETS = OUT / "assets"

# Pure by-products. Regenerated by re-running the step that made them, so they
# are never worth a confirmation prompt.
SCRATCH_DIRS = [
    ("_sheet_frames", "per-frame renders, recomposed into a sheet every run"),
    ("sprites", "unlit ComfyUI silhouette checks"),
    ("Hun2-1", "Hunyuan3D TexGen's working directory; the maps are baked into the textured .glb"),
]
SCRATCH_EXTRA = [
    (ROOT / "logs", "run logs from setup.sh / postinstall.sh and any redirected run"),
]
SCRATCH_GLOBS = [
    ("**/*_uv.npz", "UV working files written by Load 3D Mesh"),
    ("**/*.part", "interrupted downloads"),
    ("**/*.bak", "backups"),
]


def human(n: float) -> str:
    for u in ("B", "KB", "MB", "GB"):
        if n < 1024 or u == "GB":
            return f"{n:.0f}{u}" if u == "B" else f"{n:.1f}{u}"
        n /= 1024.0
    return ""


def size_of(p: Path) -> int:
    if p.is_file():
        return p.stat().st_size
    return sum(f.stat().st_size for f in p.rglob("*") if f.is_file())


def find_scratch() -> list[tuple[Path, str]]:
    hits: list[tuple[Path, str]] = []
    for name, why in SCRATCH_DIRS:
        d = OUT / name
        if d.is_dir():
            hits.append((d, why))
    for d, why in SCRATCH_EXTRA:
        if d.is_dir() and any(f for f in d.iterdir() if f.name != ".gitkeep"):
            hits.append((d, why))
    for pattern, why in SCRATCH_GLOBS:
        for f in OUT.glob(pattern):
            if ASSETS in f.parents:
                continue                      # curated copies are never scratch
            hits.append((f, why))
    return hits


def curated_files() -> set[Path]:
    if not ASSETS.is_dir():
        return set()
    return {f.resolve() for f in ASSETS.rglob("*") if f.is_file()}


def curated_sources() -> set[Path]:
    """The ORIGINAL paths that have been curated, read from each asset's
    sources.json.

    Matching on basenames instead would be wrong and dangerous: `keep` renames
    as it copies (concept.png, model.glb, rig.fbx), so the originals would never
    match their copies and --unclaimed would offer to delete the very files that
    were just curated."""
    out: set[Path] = set()
    if not ASSETS.is_dir():
        return out
    for man in ASSETS.glob("*/sources.json"):
        try:
            for rel in json.loads(man.read_text()).get("sources", []):
                out.add((ROOT / rel).resolve())
        except (OSError, ValueError):
            print(f"  ! could not read {man.relative_to(ROOT)}; treating its "
                  f"sources as unclaimed", file=sys.stderr)
    return out


def find_unclaimed() -> list[Path]:
    """Generated files outside output/assets/ that no curated copy matches."""
    claimed = curated_sources()
    scratch_roots = {OUT / n for n, _ in SCRATCH_DIRS}
    out: list[Path] = []
    for f in OUT.rglob("*"):
        if not f.is_file():
            continue
        if ASSETS in f.parents or any(r in f.parents or r == f for r in scratch_roots):
            continue
        if f.resolve() in claimed:
            continue
        out.append(f)
    return sorted(out)


# --------------------------------------------------------------------- keep

def cmd_keep(args) -> int:
    dest = ASSETS / args.name
    tex = dest / "textures"
    dest.mkdir(parents=True, exist_ok=True)

    sources: list[str] = []

    def take(src: Path, into: Path, rename: str | None = None) -> None:
        if not src.exists():
            sys.exit(f"no such file: {src}")
        into.mkdir(parents=True, exist_ok=True)
        target = into / (rename or src.name)
        if src.resolve() == target.resolve():
            # Re-curating in place, e.g. to backfill sources.json after the
            # original was swept.  Record it, do not copy a file onto itself.
            print(f"  kept  {target.relative_to(ROOT)}  (already in place)")
            sources.append(str(target.resolve().relative_to(ROOT)))
            return
        shutil.copy2(src, target)
        try:
            sources.append(str(src.resolve().relative_to(ROOT)))
        except ValueError:
            sources.append(str(src.resolve()))
        print(f"  kept  {target.relative_to(ROOT)}  ({human(size_of(target))})")

    take(Path(args.concept), dest, f"concept{Path(args.concept).suffix}")
    if args.model:
        take(Path(args.model), dest, f"model{Path(args.model).suffix}")
    if args.rig:
        take(Path(args.rig), dest, f"rig{Path(args.rig).suffix}")
    for s in args.sheets or []:
        take(Path(s), dest / "sheets")

    # Sidecar maps: an .obj's .mtl and *_albedo/_metallic/_roughness images, and
    # anything TexGen left beside the model.  A .glb embeds its textures, so this
    # is usually empty for one — which is not an error.
    if args.model:
        model = Path(args.model)
        for extra in sorted(model.parent.glob(model.stem + "*")):
            if extra == model or extra.suffix.lower() in (".npz",):
                continue
            take(extra, tex)
    for t in args.textures or []:
        take(Path(t), tex)

    man = dest / "sources.json"
    prior = []
    if man.exists():
        try:
            prior = json.loads(man.read_text()).get("sources", [])
        except ValueError:
            pass
    man.write_text(json.dumps({"name": args.name,
                               "sources": sorted(set(prior) | set(sources))}, indent=2) + "\n")
    print(f"  wrote {man.relative_to(ROOT)}  ({len(set(prior) | set(sources))} source paths)")

    print(f"\n{args.name} curated in {dest.relative_to(ROOT)}")
    print("Now: scripts/cleanup.py sweep            (dry run)")
    print("     scripts/cleanup.py sweep --delete   (scratch only)")
    return 0


# -------------------------------------------------------------------- sweep

def cmd_sweep(args) -> int:
    scratch = find_scratch()
    total = sum(size_of(p) for p, _ in scratch)
    print(f"SCRATCH — always safe, regenerated by re-running the step ({human(total)})")
    if not scratch:
        print("  (none)")
    for p, why in scratch:
        print(f"  {human(size_of(p)):>8}  {p.relative_to(ROOT)}\n            {why}")

    unclaimed = find_unclaimed()
    utotal = sum(size_of(p) for p in unclaimed)
    print(f"\nUNCLAIMED — generated, but not curated into output/assets/ ({human(utotal)}, "
          f"{len(unclaimed)} files)")
    if not curated_files():
        print("  Nothing has been curated yet, so EVERYTHING is unclaimed.")
        print("  Run `scripts/cleanup.py keep <name> --concept ... --model ...` first.")
    for p in unclaimed[:20]:
        print(f"  {human(size_of(p)):>8}  {p.relative_to(ROOT)}")
    if len(unclaimed) > 20:
        print(f"  ... and {len(unclaimed) - 20} more")

    targets = [p for p, _ in scratch]
    if args.unclaimed:
        targets += unclaimed

    if not args.delete:
        print(f"\nDry run. {human(sum(size_of(p) for p in targets))} would be removed.")
        print("Add --delete to act" + (", and --unclaimed to include the second list."
                                       if not args.unclaimed else "."))
        return 0

    if args.unclaimed and not curated_files():
        sys.exit("\nRefusing --unclaimed with nothing curated: that would delete every "
                 "asset you have made. Run `cleanup.py keep ...` first.")

    freed = 0
    for p in targets:
        try:
            n = size_of(p)
            if p.is_dir():
                shutil.rmtree(p)
            else:
                p.unlink()
        except FileNotFoundError:
            continue                      # already gone; nothing to report
        freed += n
        print(f"  removed {p.relative_to(ROOT)}")
    print(f"\nFreed {human(freed)}.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd")

    k = sub.add_parser("keep", help="curate one asset into output/assets/<name>/")
    k.add_argument("name")
    k.add_argument("--concept", required=True, help="the base image")
    k.add_argument("--model", help="the mesh (.glb/.obj), textured if you have one. "
                   "Omit for a concept-only asset that has not been through image-to-3D yet")
    k.add_argument("--rig", help="the rigged .fbx, if there is one")
    k.add_argument("--sheets", nargs="*", help="pose sheets to keep")
    k.add_argument("--textures", nargs="*", help="extra texture maps not beside the model")
    k.set_defaults(func=cmd_keep)

    s = sub.add_parser("sweep", help="report, then optionally remove")
    s.add_argument("--delete", action="store_true", help="actually remove (default: dry run)")
    s.add_argument("--unclaimed", action="store_true",
                   help="also remove generated files not curated into output/assets/")
    s.set_defaults(func=cmd_sweep)

    args = ap.parse_args()
    if not args.cmd:
        return cmd_sweep(argparse.Namespace(delete=False, unclaimed=False))
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
